# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias for piping into clibpard (e.g. 'echo -n testing | copytext', or 'cat image.png | copyimage')
alias copytext="xclip -selection clipboard -i"
alias copyimage="xclip -selection clipboard -t image/png -i"

alias del='trash-put'
alias mkdir="mkdir -pv"
alias apt-fix-pkg='sudo apt-get update && sudo apt-get autoclean && sudo apt-get clean && sudo apt-get autoremove'
alias apt-update='sudo apt-get update && sudo apt-get upgrade'
alias clear='clear && clear' # clear everything to not interfere with searches

# ring android
alias set-ring-android-armv7='export ANDROID_ABI="armeabi-v7a" && echo "ANDROID_ABI=$ANDROID_ABI"'
alias set-ring-android-armv8='export ANDROID_ABI="arm64-v8a" && echo "ANDROID_ABI=$ANDROID_ABI"'
alias set-ring-android-x86='export ANDROID_ABI="x86" && echo "ANDROID_ABI=$ANDROID_ABI"'
alias set-ring-android-x64='export ANDROID_ABI="x86_64" && echo "ANDROID_ABI=$ANDROID_ABI"'
alias set-ring-android-all='export ANDROID_ABI="armeabi-v7a arm64-v8a x86 x86_64" && echo "ANDROID_ABI=$ANDROID_ABI"'
