# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

alias del='trash-put'
alias mkdir="mkdir -pv"
alias apt-fix-pkg='sudo apt-get update && sudo apt-get autoclean && sudo apt-get clean && sudo apt-get autoremove'
alias min-bright="echo 8 | sudo tee /sys/class/backlight/intel_backlight/brightness"

# ring android
alias set-ring-arm32='export ANDROID_ABI="armeabi-v7a"'
alias set-ring-arm64='export ANDROID_ABI="arm64-v8a"'
alias set-ring-arm='export ANDROID_ABI="armeabi-v7a arm64-v8a"'
alias set-ring-intel='export ANDROID_ABI="x86 x86_64"'
alias set-ring-all='export ANDROID_ABI="armeabi-v7a arm64-v8a x86 x86_64"'
